# This is a basic workflow to help you get started with Actions

name: Python BDD SSM tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the mainline branch
on:
  pull_request:
    branches: [ mainline ]
  push:
    branches: [ mainline ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest_bdd
        pip install pytest_html
        pip install pytest-cov
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov=src/ --cov-report term --cov-report html

   #deploy:
   # runs-on: ubuntu-latest
   #  steps:
   # - uses: actions/checkout@master
   # - name: Upload file to bucket
   #   uses: zdurham/s3-upload-github-action@master
   #   with:
   #     args: --acl public-read
   #   env:
   #     FILE: ./documentation/coverage/index.html
   #     AWS_REGION: ${{ secrets.AWS_REGION }}
   #     S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
   #     S3_KEY: ${{ secrets.S3_KEY }}
   #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}   # optional: defaults to us-east-1
        #SOURCE_DIR: 'documentation'      # optional: defaults to entire repository